spring:
  application:
    name: test-server
server:
  port: 8080

mybatis.type-aliases-package: com.example.develop.vo

spring.datasource.driverClassName: com.mysql.cj.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/pandora?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: root


#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql



