spring:
  application:
    name: test-server
server:
  port: 8080


spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/pandora?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username: root
spring.datasource.password: root




#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#mybatis.type-aliases-package: com.example.develop.domain
#mybatis.config-location: classpath:mybatis/mybatis.xml
#mybatis.mapper-locations: classpath:mybatis/mapper/*.xml
